/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciabancaria.Views;

import agenciabancaria.Controllers.DBConnection;
import agenciabancaria.Controllers.Pair;
import agenciabancaria.Models.Operacao_Bancaria;
import agenciabancaria.Models.Emprestimo;
import agenciabancaria.Models.Emprestimo_Cliente;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
/**
 *
 * @author dressinha
 */
public class ClienteContaCorrente extends javax.swing.JFrame {

    /**
     * Creates new form Interface2
     */
    public ClienteContaCorrente() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TarifaContaCorrente = new javax.swing.JEditorPane();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TipoContaCorrente = new javax.swing.JEditorPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        SaldoContaCorrente = new javax.swing.JEditorPane();
        jPanelEmprestimo = new javax.swing.JPanel();
        jPanelEmprestimo1 = new javax.swing.JPanel();
        jTextFieldValorEmprestimo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonProsseguirEmp = new javax.swing.JButton();
        jButtonLimparDadosEmp = new javax.swing.JButton();
        jTextFieldParcelasEmp = new javax.swing.JTextField();
        jPanelParticiparEmprestimo = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBoxNomeCliente = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxValorEmprestimo = new javax.swing.JComboBox<>();
        jButtonParticipar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        CPFClienteCC = new javax.swing.JTextField();
        jButtonLimparParticiparEmprestimo = new javax.swing.JButton();
        jPanelPagamento = new javax.swing.JPanel();
        jPanelPagamento1 = new javax.swing.JPanel();
        jTextFieldValorPagamento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonProsseguirPagamento = new javax.swing.JButton();
        jButtonLimparDadosPagamento = new javax.swing.JButton();
        jComboBoxTipoPagamento = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldDescPagamento = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        mesPagamento = new javax.swing.JTextField();
        anoPagamento = new javax.swing.JTextField();
        diaPagamento = new javax.swing.JTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanelHome.setMaximumSize(new java.awt.Dimension(32767, 33000));

        jLabel1.setText("Bem-vindo(a)");

        jLabel2.setText("Tipo ");

        jLabel3.setText("Saldo");

        TarifaContaCorrente.setEditable(false);
        jScrollPane2.setViewportView(TarifaContaCorrente);

        jLabel10.setText("Tarifa Mensal");

        TipoContaCorrente.setEditable(false);
        jScrollPane3.setViewportView(TipoContaCorrente);

        SaldoContaCorrente.setEditable(false);
        jScrollPane4.setViewportView(SaldoContaCorrente);

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane4))
                        .addGap(23, 23, 23))))
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Home", jPanelHome);

        jTextFieldValorEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorEmprestimoActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor");

        jLabel6.setText("Parcelas");

        jButtonProsseguirEmp.setText("Prosseguir");
        jButtonProsseguirEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsseguirEmpActionPerformed(evt);
            }
        });

        jButtonLimparDadosEmp.setText("Limpar");
        jButtonLimparDadosEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparDadosEmpActionPerformed(evt);
            }
        });

        jTextFieldParcelasEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldParcelasEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEmprestimo1Layout = new javax.swing.GroupLayout(jPanelEmprestimo1);
        jPanelEmprestimo1.setLayout(jPanelEmprestimo1Layout);
        jPanelEmprestimo1Layout.setHorizontalGroup(
            jPanelEmprestimo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmprestimo1Layout.createSequentialGroup()
                .addGroup(jPanelEmprestimo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEmprestimo1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelEmprestimo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEmprestimo1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEmprestimo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldValorEmprestimo, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                            .addComponent(jTextFieldParcelasEmp)))
                    .addGroup(jPanelEmprestimo1Layout.createSequentialGroup()
                        .addContainerGap(123, Short.MAX_VALUE)
                        .addComponent(jButtonProsseguirEmp)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonLimparDadosEmp)
                        .addGap(65, 65, 65)))
                .addContainerGap())
        );
        jPanelEmprestimo1Layout.setVerticalGroup(
            jPanelEmprestimo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmprestimo1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelEmprestimo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldValorEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanelEmprestimo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldParcelasEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanelEmprestimo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProsseguirEmp)
                    .addComponent(jButtonLimparDadosEmp))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelEmprestimoLayout = new javax.swing.GroupLayout(jPanelEmprestimo);
        jPanelEmprestimo.setLayout(jPanelEmprestimoLayout);
        jPanelEmprestimoLayout.setHorizontalGroup(
            jPanelEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelEmprestimo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelEmprestimoLayout.setVerticalGroup(
            jPanelEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmprestimoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelEmprestimo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Criar Empréstimo", jPanelEmprestimo);

        jPanelParticiparEmprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelParticiparEmprestimoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanelParticiparEmprestimoMouseEntered(evt);
            }
        });

        jLabel11.setText("Nome");

        jComboBoxNomeCliente.setMaximumRowCount(50);
        jComboBoxNomeCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um Cliente" }));
        jComboBoxNomeCliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxNomeClienteItemStateChanged(evt);
            }
        });
        jComboBoxNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxNomeClienteActionPerformed(evt);
            }
        });

        jLabel12.setText("Valor");

        jComboBoxValorEmprestimo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha um Valor" }));

        jButtonParticipar.setText("Participar");
        jButtonParticipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParticiparActionPerformed(evt);
            }
        });

        jLabel13.setText("CPF");

        jButtonLimparParticiparEmprestimo.setText("Limpar");
        jButtonLimparParticiparEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparParticiparEmprestimoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelParticiparEmprestimoLayout = new javax.swing.GroupLayout(jPanelParticiparEmprestimo);
        jPanelParticiparEmprestimo.setLayout(jPanelParticiparEmprestimoLayout);
        jPanelParticiparEmprestimoLayout.setHorizontalGroup(
            jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParticiparEmprestimoLayout.createSequentialGroup()
                .addGroup(jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelParticiparEmprestimoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(36, 36, 36)
                        .addGroup(jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CPFClienteCC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxValorEmprestimo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxNomeCliente, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelParticiparEmprestimoLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButtonParticipar)
                        .addGap(47, 47, 47)
                        .addComponent(jButtonLimparParticiparEmprestimo)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanelParticiparEmprestimoLayout.setVerticalGroup(
            jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelParticiparEmprestimoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jComboBoxNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxValorEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CPFClienteCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelParticiparEmprestimoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonParticipar)
                    .addComponent(jButtonLimparParticiparEmprestimo))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Participar Emprestimo", jPanelParticiparEmprestimo);

        jTextFieldValorPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorPagamentoActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo");

        jLabel8.setText("Valor");

        jButtonProsseguirPagamento.setText("Prosseguir");
        jButtonProsseguirPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProsseguirPagamentoActionPerformed(evt);
            }
        });

        jButtonLimparDadosPagamento.setText("Limpar");
        jButtonLimparDadosPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparDadosPagamentoActionPerformed(evt);
            }
        });

        jComboBoxTipoPagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Debito", "Credito" }));
        jComboBoxTipoPagamento.setToolTipText("");
        jComboBoxTipoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoPagamentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Data");

        jTextFieldDescPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescPagamentoActionPerformed(evt);
            }
        });

        jLabel9.setText("Descrição");

        mesPagamento.setToolTipText("Mes");
        mesPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesPagamentoActionPerformed(evt);
            }
        });

        anoPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoPagamentoActionPerformed(evt);
            }
        });

        diaPagamento.setToolTipText("Dia");

        javax.swing.GroupLayout jPanelPagamento1Layout = new javax.swing.GroupLayout(jPanelPagamento1);
        jPanelPagamento1.setLayout(jPanelPagamento1Layout);
        jPanelPagamento1Layout.setHorizontalGroup(
            jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagamento1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagamento1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)
                        .addComponent(jComboBoxTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagamento1Layout.createSequentialGroup()
                        .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldDescPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelPagamento1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(mesPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(anoPagamento))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPagamento1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(23, 23, 23))
            .addGroup(jPanelPagamento1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButtonProsseguirPagamento)
                .addGap(50, 50, 50)
                .addComponent(jButtonLimparDadosPagamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPagamento1Layout.setVerticalGroup(
            jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagamento1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxTipoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldValorPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mesPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anoPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldDescPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPagamento1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonProsseguirPagamento)
                    .addComponent(jButtonLimparDadosPagamento))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelPagamentoLayout = new javax.swing.GroupLayout(jPanelPagamento);
        jPanelPagamento.setLayout(jPanelPagamentoLayout);
        jPanelPagamentoLayout.setHorizontalGroup(
            jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPagamento1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelPagamentoLayout.setVerticalGroup(
            jPanelPagamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPagamentoLayout.createSequentialGroup()
                .addComponent(jPanelPagamento1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pagamento", jPanelPagamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonProsseguirEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsseguirEmpActionPerformed
        // ENTRAR FUNCIONÁRIO
        try{
            float valor = Float.parseFloat(jTextFieldValorEmprestimo.getText());
            int parcelas = Integer.parseInt(jTextFieldParcelasEmp.getText());
            
            Emprestimo emp = new Emprestimo();
            emp.setValor(valor);
            emp.setQuantparcelas(parcelas);
            emp.setAgencia_nome(agencia_nome);
            
            String sql = "SELECT id_cliente FROM conta_cliente WHERE "
                    + "agencia_nome ='" + agencia_nome + "' AND id_conta =" + ID_conta + ";";
            
            ResultSet resposta = DBConnection.seleciona(sql);
            resposta.next();
            int id_cliente = resposta.getInt("id_cliente");
            
            int ans = DBConnection.insere(emp, "");
            if(ans != -1){
                
                sql = "SELECT CURRVAL('Seq_Emprestimo');";
                
                resposta = DBConnection.seleciona(sql);
                resposta.next();
                int id_emprestimo = resposta.getInt("currval");
              
                Emprestimo_Cliente empc = new Emprestimo_Cliente();
                empc.setId_cliente(id_cliente);
                empc.setId_emprestimo(id_emprestimo);
                
                ans = DBConnection.insere(empc, "");
                
                if(ans != -1)
                    JOptionPane.showMessageDialog(null, "Emprestimo realizado com sucesso");
                else{
                    JOptionPane.showMessageDialog(null, "Dados Incorretos");
                    LimparEmprestimo();
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
                LimparEmprestimo();
            }
                    
        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Dados Incorretos");
            LimparEmprestimo();
        }
    }//GEN-LAST:event_jButtonProsseguirEmpActionPerformed

    private void jTextFieldParcelasEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldParcelasEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParcelasEmpActionPerformed

    private void jTextFieldValorEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorEmprestimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorEmprestimoActionPerformed

    private void jButtonLimparDadosEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparDadosEmpActionPerformed
        // TODO add your handling code here:
        LimparEmprestimo();
    }//GEN-LAST:event_jButtonLimparDadosEmpActionPerformed

    private void LimparEmprestimo(){
        jTextFieldValorEmprestimo.setText("");
        jTextFieldParcelasEmp.setText("");
    }
    
    private void jTextFieldValorPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorPagamentoActionPerformed

    private void jButtonProsseguirPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProsseguirPagamentoActionPerformed
        // TODO add your handling code here:
        try{
            
            float valor = Float.parseFloat(jTextFieldValorPagamento.getText());
            int dia = Integer.parseInt(diaPagamento.getText());
            int mes = Integer.parseInt(mesPagamento.getText());
            int ano = Integer.parseInt(anoPagamento.getText());
            String descricao = jTextFieldDescPagamento.getText();
            String tipo = (String) jComboBoxTipoPagamento.getSelectedItem();
            tipo = tipo.toUpperCase();
            
            if(dia <= 0 || dia > 31 || mes <= 0 || mes > 12 || ano <= 0)
                  throw new NumberFormatException("Datas Erradas");
            
            float saldoAtual = Float.parseFloat(SaldoContaCorrente.getText());
            float diff = saldoAtual-valor;
            
            if(diff < 0){
                JOptionPane.showMessageDialog(null, "Saldo Insuficiente");
                LimparPagamento();
                return;
            }
                  
            Operacao_Bancaria op = new Operacao_Bancaria();
            op.setId_conta(ID_conta);
            op.setAgencia_nome(agencia_nome);
            op.setTipo(tipo);
            op.setValor(valor);
            op.setAno(ano);
            op.setMes(mes);
            op.setDia(dia);
            op.setDescricao(descricao);
            
            int ans = DBConnection.insere(op, "");
            
            if(ans != -1){
                JOptionPane.showMessageDialog(null, "Pagamento efetivado com sucesso");
                
                String sql = "UPDATE conta SET saldo=" + diff + " WHERE "
                        + "id_conta = " + ID_conta + " AND "
                        + "agencia_nome = '" + agencia_nome + "';";
               
                System.out.println(tipo);   
                if(tipo.equals("DEBITO")){
                    System.out.println("entrou");
                    DBConnection.atualiza(sql);
                    atualizaSaldo();
                }
                
            } else{
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
                LimparPagamento();
            }
            
        } catch (Exception e) {
            LimparPagamento();
            JOptionPane.showMessageDialog(null, "Dados Incorretos");
            System.out.println("Algo deu errado " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonProsseguirPagamentoActionPerformed

    private void jButtonLimparDadosPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparDadosPagamentoActionPerformed
        // TODO add your handling code here:
        LimparPagamento();
    }//GEN-LAST:event_jButtonLimparDadosPagamentoActionPerformed

    private void LimparPagamento(){
        jTextFieldValorPagamento.setText("");
        diaPagamento.setText("");
        mesPagamento.setText("");
        anoPagamento.setText("");
        jTextFieldDescPagamento.setText("");
    }
    
    private void jComboBoxTipoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoPagamentoActionPerformed

    private void jTextFieldDescPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescPagamentoActionPerformed

    private void mesPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesPagamentoActionPerformed

    private void anoPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoPagamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoPagamentoActionPerformed

    private void jButtonParticiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParticiparActionPerformed
        // TODO add your handling code here:
        try{
            int pos1 = jComboBoxNomeCliente.getSelectedIndex();
            String valor = jComboBoxValorEmprestimo.getItemAt(jComboBoxValorEmprestimo.getSelectedIndex());
            System.out.println(pos1);
            int id = indices.get(pos1);
            int id_emprestimo = 0;
            int id_cliente = 0;
            String cpf = CPFClienteCC.getText();
            
            String sql = "SELECT id FROM cliente WHERE cpf = '" + cpf + "';";
            ResultSet resposta = DBConnection.seleciona(sql);
            
            if(resposta.next()){
                id_cliente = resposta.getInt("id");
            }
            
            for(Pair<Integer, Float>par : valoresEmprestimos.get(id)){
                if(par.value == Float.parseFloat(valor)){
                    id_emprestimo = par.key;
                    break;
                }
            }
            
            Emprestimo_Cliente ec = new Emprestimo_Cliente();
            ec.setId_cliente(id_cliente);
            ec.setId_emprestimo(id_emprestimo);
            int ans = DBConnection.insere(ec, "");
            
            if(ans != -1)
                JOptionPane.showMessageDialog(null, "Emprestimo realizado com sucesso");
            else{
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
                LimparParticiparEmprestimo();
            }
            
        } catch(Exception e){
            e.printStackTrace();
            LimparParticiparEmprestimo();
        }
    }//GEN-LAST:event_jButtonParticiparActionPerformed

    private void jPanelParticiparEmprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelParticiparEmprestimoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelParticiparEmprestimoMouseClicked

    private void jPanelParticiparEmprestimoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelParticiparEmprestimoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanelParticiparEmprestimoMouseEntered

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
        int num = jTabbedPane1.getSelectedIndex();
        if(num == 2)    
            populaParticiparEmprestimo();
        if(num == 0)
            atualizaSaldo();
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void atualizaSaldo()
    {
        try{
            String sql = "SELECT saldo FROM conta WHERE "
                    + "id_conta =" + ID_conta + " AND "
                    + "agencia_nome='" + agencia_nome + "';";
            ResultSet resposta = DBConnection.seleciona(sql);
            Float saldo = Float.parseFloat("-1.0");
            if(resposta.next()){
                saldo = resposta.getFloat("saldo");
            }
            SaldoContaCorrente.setText(saldo.toString());
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    private void jComboBoxNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxNomeClienteActionPerformed

    private void jComboBoxNomeClienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxNomeClienteItemStateChanged
        // TODO add your handling code here:
        try{
            int pos = jComboBoxNomeCliente.getSelectedIndex();
            System.out.println(pos);
            int id = indices.get(pos);
        
            jComboBoxValorEmprestimo.removeAllItems();
            for(Pair<Integer, Float>par : valoresEmprestimos.get(id)){
            
                jComboBoxValorEmprestimo.addItem(par.value.toString());
            }
        } catch(Exception e){
            //e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBoxNomeClienteItemStateChanged

    private void jButtonLimparParticiparEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparParticiparEmprestimoActionPerformed
        // TODO add your handling code here:
        LimparParticiparEmprestimo();
    }//GEN-LAST:event_jButtonLimparParticiparEmprestimoActionPerformed

    private void LimparParticiparEmprestimo(){
        CPFClienteCC.setText("");
    }
    
    private void populaParticiparEmprestimo()
    {
        String sql = "SELECT C.id, C.nome, E.id_emprestimo, E.valor FROM " +
                    "(cliente C INNER JOIN" +
                    "   (emprestimo_cliente EC INNER JOIN emprestimo E " +
                            "ON EC.id_emprestimo = E.id_emprestimo) " +
                        "ON EC.id_cliente = C.id)";
      
        nomesClientesEmprestimos = new HashMap<>();
        valoresEmprestimos = new HashMap<>();
     
        jComboBoxNomeCliente.removeAllItems();
        
        indices = new HashMap<>();

        try{
            ResultSet resposta = DBConnection.seleciona(sql);
                        
            while(resposta.next())
            {
                int id = resposta.getInt("id");
                String nome = resposta.getString("nome");
                int id_emprestimo = resposta.getInt("id_emprestimo");
                Float valor = resposta.getFloat("valor");
                
                if(valoresEmprestimos.get(id) == null)
                    valoresEmprestimos.put(id, new ArrayList<>());
                
                nomesClientesEmprestimos.put(id, nome);
                valoresEmprestimos.get(id).add(new Pair<Integer, Float>(id_emprestimo, valor));
                
            }
            
            int indice = 0;
            Set<Integer> aux = nomesClientesEmprestimos.keySet();
            for(int id : aux){
                
                jComboBoxNomeCliente.addItem(nomesClientesEmprestimos.get(id));
                indices.put(indice, id);
                indice++;
            }
    
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteContaCorrente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteContaCorrente().setVisible(true);
            }
        });
    }

    public JEditorPane getTarifaContaCorrente() {
        return TarifaContaCorrente;
    }

    public JEditorPane getSaldoContaCorrente() {
        return SaldoContaCorrente;
    }

    public void setSaldoContaCorrente(JEditorPane SaldoContaCorrente) {
        this.SaldoContaCorrente = SaldoContaCorrente;
    }

    public void setTarifaContaCorrente(JEditorPane TarifaContaCorrente) {
        this.TarifaContaCorrente = TarifaContaCorrente;
    }

    public JEditorPane getTipoContaCorrente() {
        return TipoContaCorrente;
    }

    public void setTipoContaCorrente(JEditorPane TipoContaCorrente) {
        this.TipoContaCorrente = TipoContaCorrente;
    }

    public int getID_conta() {
        return ID_conta;
    }

    public void setID_conta(int ID_conta) {
        this.ID_conta = ID_conta;
    }

    public String getAgencia_nome() {
        return agencia_nome;
    }

    public void setAgencia_nome(String agencia_nome) {
        this.agencia_nome = agencia_nome;
    }

    private int ID_conta;
    private String agencia_nome;
    private Map<Integer, Integer >indices;
    private Map<Integer, ArrayList< Pair<Integer, Float> > >valoresEmprestimos;
    private Map<Integer, String>nomesClientesEmprestimos;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CPFClienteCC;
    private javax.swing.JEditorPane SaldoContaCorrente;
    private javax.swing.JEditorPane TarifaContaCorrente;
    private javax.swing.JEditorPane TipoContaCorrente;
    private javax.swing.JTextField anoPagamento;
    private javax.swing.JTextField diaPagamento;
    private javax.swing.JButton jButtonLimparDadosEmp;
    private javax.swing.JButton jButtonLimparDadosPagamento;
    private javax.swing.JButton jButtonLimparParticiparEmprestimo;
    private javax.swing.JButton jButtonParticipar;
    private javax.swing.JButton jButtonProsseguirEmp;
    private javax.swing.JButton jButtonProsseguirPagamento;
    private javax.swing.JComboBox<String> jComboBoxNomeCliente;
    private javax.swing.JComboBox<String> jComboBoxTipoPagamento;
    private javax.swing.JComboBox<String> jComboBoxValorEmprestimo;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanelEmprestimo;
    private javax.swing.JPanel jPanelEmprestimo1;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelPagamento;
    private javax.swing.JPanel jPanelPagamento1;
    private javax.swing.JPanel jPanelParticiparEmprestimo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldDescPagamento;
    private javax.swing.JTextField jTextFieldParcelasEmp;
    private javax.swing.JTextField jTextFieldValorEmprestimo;
    private javax.swing.JTextField jTextFieldValorPagamento;
    private javax.swing.JTextField mesPagamento;
    // End of variables declaration//GEN-END:variables
}
