/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciabancaria.Views;

import agenciabancaria.Controllers.DBConnection;
import agenciabancaria.Models.Cliente;
import agenciabancaria.Models.Conta;
import agenciabancaria.Models.Conta_Cliente;
import agenciabancaria.Models.Corrente;
import agenciabancaria.Models.Poupanca;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author dressinha
 */
public class Funcionario extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceFuncionario
     */
    public Funcionario() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldCPFCliente = new javax.swing.JTextField();
        jTextFieldEnderecoCliente = new javax.swing.JTextField();
        jTextFieldEstadoCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCidadeCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jButtonLimparCliente = new javax.swing.JButton();
        jCheckBoxIsGerente = new javax.swing.JCheckBox();
        jTextFieldDiaCliente = new javax.swing.JTextField();
        jTextFieldMesCliente = new javax.swing.JTextField();
        jTextFieldAnoCliente = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCPFCC = new javax.swing.JTextField();
        jTextFieldAgenciaCC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTarifaMensalCC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonCadastraCC = new javax.swing.JButton();
        jButtonLimparCC = new javax.swing.JButton();
        jTextFieldDiaCC = new javax.swing.JTextField();
        jTextFieldMesCC = new javax.swing.JTextField();
        jTextFieldAnoCC = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldCPFCP = new javax.swing.JTextField();
        jTextFieldAgenciaCP = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldTarifaMensalCP = new javax.swing.JTextField();
        jButtonCadastraCP = new javax.swing.JButton();
        jButtonLimparCP = new javax.swing.JButton();
        jTextFieldDiaCP = new javax.swing.JTextField();
        jTextFieldMesCP = new javax.swing.JTextField();
        jTextFieldAnoCP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AgenciaAdicionarCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ContaAdicionarCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CPFAdicionarCliente = new javax.swing.JTextField();
        jButtonAdicionarCliente = new javax.swing.JButton();
        jButtonLimparAdicionarCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeClienteActionPerformed(evt);
            }
        });

        jTextFieldCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFClienteActionPerformed(evt);
            }
        });

        jTextFieldEnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoClienteActionPerformed(evt);
            }
        });

        jTextFieldEstadoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEstadoClienteActionPerformed(evt);
            }
        });

        jLabel10.setText("Nome");

        jLabel11.setText("CPF");

        jLabel12.setText("Data Nascimento");

        jLabel2.setText("Endereço");

        jLabel3.setText("Estado");

        jTextFieldCidadeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeClienteActionPerformed(evt);
            }
        });

        jLabel13.setText("Cidade");

        jButtonCadastrarCliente.setText("Cadastrar");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        jButtonLimparCliente.setText("Limpar");
        jButtonLimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparClienteActionPerformed(evt);
            }
        });

        jCheckBoxIsGerente.setText("Gerente");
        jCheckBoxIsGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxIsGerenteActionPerformed(evt);
            }
        });

        jTextFieldDiaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiaClienteActionPerformed(evt);
            }
        });

        jTextFieldMesCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesClienteActionPerformed(evt);
            }
        });

        jTextFieldAnoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnoClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13)
                    .addComponent(jCheckBoxIsGerente))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCPFCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEnderecoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEstadoCliente, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCidadeCliente, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButtonCadastrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                        .addComponent(jButtonLimparCliente)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldDiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnoCliente)
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldDiaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAnoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEstadoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarCliente)
                    .addComponent(jButtonLimparCliente)
                    .addComponent(jCheckBoxIsGerente))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cria Cliente", jPanel4);

        jLabel15.setText("CPF");

        jTextFieldCPFCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFCCActionPerformed(evt);
            }
        });

        jTextFieldAgenciaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgenciaCCActionPerformed(evt);
            }
        });

        jLabel1.setText("Agência");

        jTextFieldTarifaMensalCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTarifaMensalCCActionPerformed(evt);
            }
        });

        jLabel5.setText("Tarifa Mensal");

        jLabel6.setText("Data");

        jButtonCadastraCC.setText("Cadastrar");
        jButtonCadastraCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraCCActionPerformed(evt);
            }
        });

        jButtonLimparCC.setText("Limpar");
        jButtonLimparCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCCActionPerformed(evt);
            }
        });

        jTextFieldDiaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiaCCActionPerformed(evt);
            }
        });

        jTextFieldMesCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAgenciaCC, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jTextFieldCPFCC)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldDiaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMesCC, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnoCC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldTarifaMensalCC, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButtonCadastraCC)
                .addGap(51, 51, 51)
                .addComponent(jButtonLimparCC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldCPFCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAgenciaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldTarifaMensalCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDiaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMesCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAnoCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastraCC)
                    .addComponent(jButtonLimparCC))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cria Conta Corrente", jPanel1);

        jLabel16.setText("CPF");

        jTextFieldCPFCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPFCPActionPerformed(evt);
            }
        });

        jTextFieldAgenciaCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAgenciaCPActionPerformed(evt);
            }
        });

        jLabel7.setText("Agência");

        jLabel9.setText("Taxa Juros");

        jLabel14.setText("Data");

        jTextFieldTarifaMensalCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTarifaMensalCPActionPerformed(evt);
            }
        });

        jButtonCadastraCP.setText("Cadastrar");
        jButtonCadastraCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastraCPActionPerformed(evt);
            }
        });

        jButtonLimparCP.setText("Limpar");
        jButtonLimparCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCPActionPerformed(evt);
            }
        });

        jTextFieldDiaCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiaCPActionPerformed(evt);
            }
        });

        jTextFieldMesCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMesCPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel7))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCPFCP, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                            .addComponent(jTextFieldAgenciaCP)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addGap(83, 83, 83)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextFieldDiaCP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMesCP, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnoCP))
                            .addComponent(jTextFieldTarifaMensalCP))))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jButtonCadastraCP)
                .addGap(50, 50, 50)
                .addComponent(jButtonLimparCP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldCPFCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAgenciaCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldTarifaMensalCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDiaCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMesCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldAnoCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastraCP)
                    .addComponent(jButtonLimparCP))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cria Conta Poupança", jPanel2);

        jLabel4.setText("Agencia");

        jLabel8.setText("Conta");

        jLabel17.setText("CPF");

        jButtonAdicionarCliente.setText("Adicionar");
        jButtonAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarClienteActionPerformed(evt);
            }
        });

        jButtonLimparAdicionarCliente.setText("Limpar");
        jButtonLimparAdicionarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparAdicionarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel17))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AgenciaAdicionarCliente)
                            .addComponent(ContaAdicionarCliente)
                            .addComponent(CPFAdicionarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jButtonAdicionarCliente)
                        .addGap(64, 64, 64)
                        .addComponent(jButtonLimparAdicionarCliente)))
                .addContainerGap(195, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AgenciaAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ContaAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(CPFAdicionarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdicionarCliente)
                    .addComponent(jButtonLimparAdicionarCliente))
                .addGap(66, 66, 66))
        );

        jTabbedPane1.addTab("Adicionar Cliente em Conta", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxIsGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxIsGerenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxIsGerenteActionPerformed

    private void jTextFieldCidadeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeClienteActionPerformed

    private void jTextFieldEstadoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEstadoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEstadoClienteActionPerformed

    private void jTextFieldEnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoClienteActionPerformed

    private void jTextFieldCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFClienteActionPerformed

    private void jTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeClienteActionPerformed

    private void jTextFieldCPFCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFCCActionPerformed

    private void jTextFieldAgenciaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgenciaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgenciaCCActionPerformed

    private void jButtonLimparCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCCActionPerformed
        // TODO add your handling code here:
        LimparCC();
    }//GEN-LAST:event_jButtonLimparCCActionPerformed

    private void LimparCC(){
        jTextFieldCPFCC.setText("");
        jTextFieldAgenciaCC.setText("");
        jTextFieldTarifaMensalCC.setText("");
        jTextFieldDiaCC.setText("");
        jTextFieldMesCC.setText("");
        jTextFieldAnoCC.setText("");
    }
    
    private void jButtonCadastraCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraCCActionPerformed
        // TODO add your handling code here:
        try{
            String cpf = jTextFieldCPFCC.getText();
            float tarifa = Float.parseFloat(jTextFieldTarifaMensalCC.getText());
            int dia = Integer.parseInt(jTextFieldDiaCC.getText());
            int mes = Integer.parseInt(jTextFieldMesCC.getText());
            int ano = Integer.parseInt(jTextFieldAnoCC.getText());
            String agencia_nome = jTextFieldAgenciaCC.getText();
            
            Conta con = new Conta();
            con.setAgencia_nome(agencia_nome);
            con.setAno(ano);
            con.setDia(dia);
            con.setMes(mes);
            con.setSaldo(0);
            con.setTipo_conta("corrente");
            
            int ans = DBConnection.insere(con, "");
            
            if(ans != -1){
                
                String sql = "SELECT CURRVAL('Seq_Conta');";
                ResultSet resultado = DBConnection.seleciona(sql);
                int id_conta =0;
                while(resultado.next()){
                 id_conta = resultado.getInt("currval");
                }
                sql = "SELECT id FROM cliente WHERE cpf ='" + cpf + "';";
                resultado = DBConnection.seleciona(sql);
                int id_cliente = 0;
                while(resultado.next()){
                    id_cliente = resultado.getInt("id");
                }
                        
                Conta_Cliente concli = new Conta_Cliente();
                concli.setAgencia_nome(agencia_nome);
                concli.setId_cliente(id_cliente);
                concli.setId_conta(id_conta);
                ans = DBConnection.insere(concli, "");
                //}
                if(ans != -1){
                    Corrente corr = new Corrente();
                    corr.setAgencia_nome(agencia_nome);
                    corr.setId_conta(id_conta);
                    corr.setTarifa_mensal(tarifa);
                    ans = DBConnection.insere(corr, "");
                    
                    if(ans != -1)
                        JOptionPane.showMessageDialog(null, "Conta Criada com Sucesso");
                    else
                        JOptionPane.showMessageDialog(null, "Dados Incorretos");
                        
                } else {
                    JOptionPane.showMessageDialog(null, "Dados Incorretos");
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
            
        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Dados Incorretos");
            LimparCC();
        }
    }//GEN-LAST:event_jButtonCadastraCCActionPerformed

    private void jTextFieldCPFCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPFCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPFCPActionPerformed

    private void jTextFieldAgenciaCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAgenciaCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAgenciaCPActionPerformed

    private void jTextFieldTarifaMensalCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTarifaMensalCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTarifaMensalCPActionPerformed

    private void jButtonCadastraCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastraCPActionPerformed
        // TODO add your handling code here:
        try{
            String cpf = jTextFieldCPFCP.getText();
            float tarifa = Float.parseFloat(jTextFieldTarifaMensalCP.getText());
            int dia = Integer.parseInt(jTextFieldDiaCP.getText());
            int mes = Integer.parseInt(jTextFieldMesCP.getText());
            int ano = Integer.parseInt(jTextFieldAnoCP.getText());
            String agencia_nome = jTextFieldAgenciaCP.getText();
            
            Conta con = new Conta();
            con.setAgencia_nome(agencia_nome);
            con.setAno(ano);
            con.setDia(dia);
            con.setMes(mes);
            con.setSaldo(0);
            con.setTipo_conta("poupanca");
            
            int ans = DBConnection.insere(con, "");
            
            if(ans != -1){
                
                String sql = "SELECT CURRVAL('Seq_Conta');";
                ResultSet resultado = DBConnection.seleciona(sql);
                int id_conta =0;
                while(resultado.next()){
                 id_conta = resultado.getInt("currval");
                }
                sql = "SELECT id FROM cliente WHERE cpf ='" + cpf + "';";
                resultado = DBConnection.seleciona(sql);
                int id_cliente = 0;
                while(resultado.next()){
                    id_cliente = resultado.getInt("id");
                }
                        
                Conta_Cliente concli = new Conta_Cliente();
                concli.setAgencia_nome(agencia_nome);
                concli.setId_cliente(id_cliente);
                concli.setId_conta(id_conta);
                ans = DBConnection.insere(concli, "");
                //}
                if(ans != -1){
                    Poupanca pou = new Poupanca();
                    pou.setAgencia_nome(agencia_nome);
                    pou.setId_conta(id_conta);
                    pou.setTaxa_juros(tarifa);
                    ans = DBConnection.insere(pou, "");
                    
                    if(ans != -1)
                        JOptionPane.showMessageDialog(null, "Conta Criada com Sucesso");
                    else
                        JOptionPane.showMessageDialog(null, "Dados Incorretos");
                        
                } else {
                    JOptionPane.showMessageDialog(null, "Dados Incorretos");
                }
            }
            else
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
            
        } catch(Exception e){
            e.printStackTrace();
            LimparCP();
            JOptionPane.showMessageDialog(null, "Dados Incorretos");
        }
    }//GEN-LAST:event_jButtonCadastraCPActionPerformed

    private void jButtonLimparCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCPActionPerformed
        // TODO add your handling code here:
        jTextFieldCPFCP.setText("");
        jTextFieldAgenciaCP.setText("");
        jTextFieldTarifaMensalCP.setText("");
        jTextFieldDiaCP.setText("");
        jTextFieldMesCP.setText("");
        jTextFieldAnoCP.setText("");
    }//GEN-LAST:event_jButtonLimparCPActionPerformed

    private void LimparCP(){
        jTextFieldCPFCP.setText("");
        jTextFieldAgenciaCP.setText("");
        jTextFieldTarifaMensalCP.setText("");
        jTextFieldDiaCP.setText("");
        jTextFieldMesCP.setText("");
        jTextFieldAnoCP.setText("");
    }
    
    private void jButtonLimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparClienteActionPerformed
        // TODO add your handling code here:
        LimparCliente();
    }//GEN-LAST:event_jButtonLimparClienteActionPerformed

    private void LimparCliente(){
        jTextFieldNomeCliente.setText("");
        jTextFieldCPFCliente.setText("");
        jTextFieldDiaCliente.setText("");
        jTextFieldMesCliente.setText("");
        jTextFieldAnoCliente.setText("");
        jTextFieldEnderecoCliente.setText("");
        jTextFieldEstadoCliente.setText("");
        jTextFieldCidadeCliente.setText("");
        jCheckBoxIsGerente.setSelected(false);
    }
    
    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
        // TODO add your handling code here:
        try{
            String nome = jTextFieldNomeCliente.getText();
            String cpf = jTextFieldCPFCliente.getText();
            int dia = Integer.parseInt(jTextFieldDiaCliente.getText());
            int mes = Integer.parseInt(jTextFieldMesCliente.getText());
            int ano = Integer.parseInt(jTextFieldAnoCliente.getText());
            String endereco = jTextFieldEnderecoCliente.getText();
            String estado = jTextFieldEstadoCliente.getText();
            String cidade = jTextFieldCidadeCliente.getText();
            Boolean ehGerente = jCheckBoxIsGerente.isSelected();
            
            if(dia <= 0 || dia > 31 || mes <= 0 || mes > 12 || ano <= 0 || cpf.length() != 11 || new Double(cpf).isNaN())
                  throw new NumberFormatException("Datas Erradas");
            
            Cliente cli = new Cliente();
            cli.setNome(nome);
            cli.setCpf(cpf);
            cli.setDia(dia);
            cli.setMes(mes);
            cli.setAno(ano);
            cli.setEndereco(endereco);
            cli.setEstado(estado);
            cli.setCidade(cidade);
            cli.setGerente( ehGerente == false ? -1 : NumFuncionario );
            int ans = DBConnection.insere(cli, "");
            
            if(ans != -1)
                JOptionPane.showMessageDialog(null, "Cliente Criado com Sucesso");
            else
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
            
        } catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Dados Incorretos");
            LimparCliente();
        }
    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    private void jTextFieldMesClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMesClienteActionPerformed

    private void jTextFieldDiaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiaClienteActionPerformed

    private void jTextFieldAnoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnoClienteActionPerformed

    private void jTextFieldMesCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMesCCActionPerformed

    private void jTextFieldDiaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiaCCActionPerformed

    private void jTextFieldTarifaMensalCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTarifaMensalCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTarifaMensalCCActionPerformed

    private void jTextFieldDiaCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiaCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiaCPActionPerformed

    private void jTextFieldMesCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMesCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMesCPActionPerformed

    private void jButtonAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarClienteActionPerformed
        // TODO add your handling code here:
        try{
            
            String agencia_nome = AgenciaAdicionarCliente.getText();
            int id_conta = Integer.parseInt(ContaAdicionarCliente.getText());
            String cpf = CPFAdicionarCliente.getText();
            
            String sql = "SELECT id FROM cliente WHERE cpf ='" + cpf + "';";
            ResultSet resultado = DBConnection.seleciona(sql);
            int id_cliente = 0;
            while(resultado.next()){
                id_cliente = resultado.getInt("id");
            }
            
            Conta_Cliente concli = new Conta_Cliente();
            concli.setAgencia_nome(agencia_nome);
            concli.setId_cliente(id_cliente);
            concli.setId_conta(id_conta);
            int ans = DBConnection.insere(concli, "");
            
             if(ans != -1)
                JOptionPane.showMessageDialog(null, "Sucesso ao Adicionar o Cliente a Conta");
            else
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
            
        } catch(Exception e){
            e.printStackTrace();
            LimparAdicionarCliente();
            JOptionPane.showMessageDialog(null, "Dados Incorretos");
        }
    }//GEN-LAST:event_jButtonAdicionarClienteActionPerformed

    private void jButtonLimparAdicionarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparAdicionarClienteActionPerformed
        // TODO add your handling code here:
        LimparAdicionarCliente();
    }//GEN-LAST:event_jButtonLimparAdicionarClienteActionPerformed

    private void LimparAdicionarCliente(){
        AgenciaAdicionarCliente.setText("");
        CPFAdicionarCliente.setText("");
        ContaAdicionarCliente.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario().setVisible(true);
            }
        });
    }

    public int getNumFuncionario() {
        return NumFuncionario;
    }

    public void setNumFuncionario(int NumFuncionario) {
        this.NumFuncionario = NumFuncionario;
    }
 
    private int NumFuncionario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgenciaAdicionarCliente;
    private javax.swing.JTextField CPFAdicionarCliente;
    private javax.swing.JTextField ContaAdicionarCliente;
    private javax.swing.JButton jButtonAdicionarCliente;
    private javax.swing.JButton jButtonCadastraCC;
    private javax.swing.JButton jButtonCadastraCP;
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonLimparAdicionarCliente;
    private javax.swing.JButton jButtonLimparCC;
    private javax.swing.JButton jButtonLimparCP;
    private javax.swing.JButton jButtonLimparCliente;
    private javax.swing.JCheckBox jCheckBoxIsGerente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextFieldAgenciaCC;
    private javax.swing.JTextField jTextFieldAgenciaCP;
    private javax.swing.JTextField jTextFieldAnoCC;
    private javax.swing.JTextField jTextFieldAnoCP;
    private javax.swing.JTextField jTextFieldAnoCliente;
    private javax.swing.JTextField jTextFieldCPFCC;
    private javax.swing.JTextField jTextFieldCPFCP;
    private javax.swing.JTextField jTextFieldCPFCliente;
    private javax.swing.JTextField jTextFieldCidadeCliente;
    private javax.swing.JTextField jTextFieldDiaCC;
    private javax.swing.JTextField jTextFieldDiaCP;
    private javax.swing.JTextField jTextFieldDiaCliente;
    private javax.swing.JTextField jTextFieldEnderecoCliente;
    private javax.swing.JTextField jTextFieldEstadoCliente;
    private javax.swing.JTextField jTextFieldMesCC;
    private javax.swing.JTextField jTextFieldMesCP;
    private javax.swing.JTextField jTextFieldMesCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldTarifaMensalCC;
    private javax.swing.JTextField jTextFieldTarifaMensalCP;
    // End of variables declaration//GEN-END:variables
}
