/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agenciabancaria.Views;

import agenciabancaria.Controllers.DBConnection;
import agenciabancaria.Views.ClientePoupanca;
import agenciabancaria.Views.ClienteContaCorrente;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dressinha
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        AgenciaCliente = new javax.swing.JTextField();
        ContaCliente = new javax.swing.JTextField();
        SenhaCliente = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EntrarCliente = new javax.swing.JButton();
        LimparCliente = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        IDFuncionario = new javax.swing.JTextField();
        SenhaFuncionario = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EntrarFuncionario = new javax.swing.JButton();
        LimparFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco UFU");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        AgenciaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaClienteActionPerformed(evt);
            }
        });

        SenhaCliente.setText("jPasswordField1");
        SenhaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaClienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Agência");

        jLabel2.setText("Conta");

        jLabel3.setText("Senha");

        EntrarCliente.setText("Entrar");
        EntrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarClienteActionPerformed(evt);
            }
        });

        LimparCliente.setText("Limpar");
        LimparCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(AgenciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ContaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(EntrarCliente)
                                .addGap(18, 18, 18)
                                .addComponent(LimparCliente))
                            .addComponent(SenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AgenciaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SenhaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntrarCliente)
                    .addComponent(LimparCliente))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cliente", jPanel4);

        SenhaFuncionario.setText("jPasswordField******");
        SenhaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaFuncionarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Acesso exclusivo para funcionários.");

        jLabel5.setText("ID");

        jLabel6.setText("Senha");

        EntrarFuncionario.setText("Entrar");
        EntrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarFuncionarioActionPerformed(evt);
            }
        });

        LimparFuncionario.setText("Limpar");
        LimparFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(EntrarFuncionario)
                            .addGap(18, 18, 18)
                            .addComponent(LimparFuncionario))
                        .addComponent(SenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IDFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(41, 41, 41))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(SenhaFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EntrarFuncionario)
                    .addComponent(LimparFuncionario))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Funcionário", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgenciaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgenciaClienteActionPerformed
        // AGÊNCIA CLIENTE
    }//GEN-LAST:event_AgenciaClienteActionPerformed

    private void SenhaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaClienteActionPerformed
        // SENHA genérica para CLIENTE
    }//GEN-LAST:event_SenhaClienteActionPerformed

    private void EntrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarClienteActionPerformed
         
        try{
            int numContaCliente = Integer.parseInt(ContaCliente.getText());
            
            String sql = "SELECT * FROM conta WHERE id_conta =" + numContaCliente + " AND "
                    + "agencia_nome = '" + AgenciaCliente.getText() + "';";
            
            ResultSet resposta, resposta2;
            resposta = DBConnection.seleciona(sql);
            
            if(resposta.next()){
                String tipo = resposta.getString("tipo_conta");
                String saldo = resposta.getString("saldo");
                
                if(tipo.equals("corrente")) {
                            
                    sql = "SELECT * FROM corrente WHERE id_conta =" + numContaCliente + " AND "
                            + "agencia_nome = '" + AgenciaCliente.getText() + "';";
                    resposta2 = DBConnection.seleciona(sql);
                    resposta2.next();
                    
                    InterfaceContaCorrente.setID_conta(numContaCliente);
                    InterfaceContaCorrente.setAgencia_nome(AgenciaCliente.getText());
                    InterfaceContaCorrente.getTipoContaCorrente().setText("Corrente");
                    InterfaceContaCorrente.getSaldoContaCorrente().setText(saldo);
                    InterfaceContaCorrente.getTarifaContaCorrente().setText(resposta2.getString("tarifa_mensal"));
                    InterfaceContaCorrente.setVisible(true);
                
                } else if(tipo.equals("poupanca")){
                    
                    sql = "SELECT * FROM poupanca WHERE id_conta =" + numContaCliente + " AND "
                            + "agencia_nome = '" + AgenciaCliente.getText() + "';";
                    resposta2 = DBConnection.seleciona(sql);
                    resposta2.next();
                    
                    InterfacePoupanca.getTipoPoupanca().setText("Poupanca");
                    InterfacePoupanca.getSaldoPoupanca().setText(saldo);
                    InterfacePoupanca.getTaxaJurosPoupanca().setText(resposta2.getString("taxa_juros"));
                    InterfacePoupanca.setVisible(true);
                }
                
            } else{
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
                LimparCliente();
            }
            
        } catch(Exception e){
            System.out.println("Nao foi possivel executar a consulta");
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Dados Incorretos");
            LimparCliente();
        }
    }//GEN-LAST:event_EntrarClienteActionPerformed
    
    private void SenhaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaFuncionarioActionPerformed
        // SENHA genérica para FUNCIONÁRIO
    }//GEN-LAST:event_SenhaFuncionarioActionPerformed

    private void EntrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarFuncionarioActionPerformed
        // ENTRAR FUNCIONÁRIO
        try{
            int numFuncionario = Integer.parseInt(IDFuncionario.getText());
            
            String sql = "SELECT * FROM funcionario WHERE numfunc =" + numFuncionario + ";";
            ResultSet resposta = DBConnection.seleciona(sql);
            
            if(resposta.next()){
                InterfaceFuncionario.setNumFuncionario(numFuncionario);
                InterfaceFuncionario.setVisible(true);
            } else{
                JOptionPane.showMessageDialog(null, "Dados Incorretos");
                LimparFuncionario();
            }
            
        } catch(Exception e){
            System.out.println("Nao foi possivel executar a consulta");
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Dados Incorretos");
            LimparFuncionario();
        }
    }//GEN-LAST:event_EntrarFuncionarioActionPerformed

    private void LimparClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparClienteActionPerformed
        // TODO add your handling code here:
        LimparCliente();
    }//GEN-LAST:event_LimparClienteActionPerformed

    private void LimparCliente(){
        AgenciaCliente.setText("");
        ContaCliente.setText("");
        SenhaCliente.setText("12345678");
    }
    
    private void LimparFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparFuncionarioActionPerformed
        // TODO add your handling code here:
        LimparFuncionario();
    }//GEN-LAST:event_LimparFuncionarioActionPerformed
                                    
    private void LimparFuncionario(){
        IDFuncionario.setText("");
        SenhaFuncionario.setText("12345678");
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        InterfaceContaCorrente = new ClienteContaCorrente();
        InterfacePoupanca = new ClientePoupanca();
        InterfaceFuncionario = new Funcionario();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    private static ClienteContaCorrente InterfaceContaCorrente;
    private static ClientePoupanca InterfacePoupanca;
    private static Funcionario InterfaceFuncionario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgenciaCliente;
    private javax.swing.JTextField ContaCliente;
    private javax.swing.JButton EntrarCliente;
    private javax.swing.JButton EntrarFuncionario;
    private javax.swing.JTextField IDFuncionario;
    private javax.swing.JButton LimparCliente;
    private javax.swing.JButton LimparFuncionario;
    private javax.swing.JPasswordField SenhaCliente;
    private javax.swing.JPasswordField SenhaFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
